//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComptabilitePFE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class I2S_Compta2Entities : DbContext
    {
        public I2S_Compta2Entities()
            : base("name=I2S_Compta2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Exercice> Exercice { get; set; }
        public virtual DbSet<Journal> Journal { get; set; }
        public virtual DbSet<LignePieceComptable> LignePieceComptable { get; set; }
        public virtual DbSet<ParametrageBilan> ParametrageBilan { get; set; }
        public virtual DbSet<ParametrageEtatResultat> ParametrageEtatResultat { get; set; }
        public virtual DbSet<PieceComptable> PieceComptable { get; set; }
        public virtual DbSet<PlanComptable> PlanComptable { get; set; }
        public virtual DbSet<RubriqueBilan> RubriqueBilan { get; set; }
        public virtual DbSet<RubriqueEtatResultat> RubriqueEtatResultat { get; set; }
        public virtual DbSet<Societe> Societe { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
