//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComptabilitePFE
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Exercice
    {
        public string CodeSociete { get; set; }

        [StringLength(4, ErrorMessage = "Name length can't be more than 8.")]
        [Required(ErrorMessage = "Ce champ est obligatoire")]
        [Display(Name = "Code exercice")]
        public string CodeExercice { get; set; }

        [Required(ErrorMessage = "Ce champ est obligatoire")]
        [DataType(DataType.Date)]
        public System.DateTime DateDebut { get; set; }

        [Required(ErrorMessage = "Ce champ est obligatoire")]
        [DataType(DataType.Date)]
        public System.DateTime DateFin { get; set; }

        public bool Cloturer { get; set; }

        public string TypeSaisie { get; set; }
    
        public virtual Exercice Exercice1 { get; set; }
        public virtual Exercice Exercice2 { get; set; }
    }
}
