//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComptabilitePFE
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Journal
    {
        public string CodeSociete { get; set; }

        [StringLength(5, ErrorMessage = "5 caractéres")]
        [Required(ErrorMessage = "Ce champ est obligatoire")]
        public string CodeJournal { get; set; }

        [StringLength(150, ErrorMessage = "150 caractéres")]
        [Required(ErrorMessage = "*")]
        public string Libelle { get; set; }

        public bool AutoriserControle { get; set; }

        public string NumeroCompte { get; set; }

        public bool Tresorerie { get; set; }

        public bool Ouverture { get; set; }
    
        public virtual Societe Societe { get; set; }
    }
}
