//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComptabilitePFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class LignePieceComptable
    {
        public string CodeSociete { get; set; }
        public string CodePiece { get; set; }
        public string CodeJournal { get; set; }
        public string CodeExercice { get; set; }
        public string NumeroCompte { get; set; }
        public int NumeroOrdre { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> DateReference { get; set; }
        public string NumeroLettrage { get; set; }
        public string NumeroRapprochement { get; set; }
    
        public virtual PieceComptable PieceComptable { get; set; }
    }
}
