//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComptabilitePFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrageBilan
    {
        public string CodeRubrique { get; set; }
        public string NumeroCompte { get; set; }
        public string Sens { get; set; }
    
        public virtual RubriqueBilan RubriqueBilan { get; set; }
    }
}
