//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComptabilitePFE
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PlanComptable
    {
        public string CodeSociete { get; set; }

        [StringLength(10, ErrorMessage = "10 caractéres")]
        [Required(ErrorMessage = "Ce champ est obligatoire")]
        public string NumeroCompte { get; set; }

        [StringLength(200, ErrorMessage = "200 caractéres")]
        [Required(ErrorMessage = "Ce champ est obligatoire")]
        public string Libelle { get; set; }

        public string TypeCompte { get; set; }
    }
}
