//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComptabilitePFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class RubriqueEtatResultat
    {
        public string CodeRubrique { get; set; }
        public string CodeRubriqueParent { get; set; }
        public string Libelle { get; set; }
        public string Nature { get; set; }
        public string Type { get; set; }
        public string Note { get; set; }
        public string Signe { get; set; }
        public bool Justification { get; set; }
    }
}
