//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComptabilitePFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Societe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Societe()
        {
            this.Journals = new HashSet<Journal>();
        }
    
        public string CodeSociete { get; set; }
        public string CodeClient { get; set; }
        public string RaisonSociete { get; set; }
        public decimal CapitalSociete { get; set; }
        public string Adresse { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Email { get; set; }
        public string MatriculeFiscale { get; set; }
        public string Observation { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journal> Journals { get; set; }
    }
}
